### ISSUE TITLE
Guj Speech software

### ISSUE THREAD

**Issue by parthdjshah** [sutariyaraj/sutariyaraj#2]
Hi Raj,

When I am running the speech recognition software, I get the following errors:

deepspeech: error: ambiguous option: --lm could match --lm_alpha, --lm_beta
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\1PBC\3SW\python39\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\1PBC\3SW\python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\1PBC\3SW\python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\1PBC\3SW\python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\1PBC\3SW\python39\lib\tkinter\__init__.py", line 1885, in __call__
    return self.func(*args)
  File "C:\Users\parth.shah\Downloads\gujarati_speech_recognition-master\gujarati_speech_recognition-master\gui.py", line 137, in transcribing
    response = duckduckgo_api(transcription)
  File "C:\Users\parth.shah\Downloads\gujarati_speech_recognition-master\gujarati_speech_recognition-master\gui.py", line 344, in duckduckgo_api
    json_response = response.json()
  File "D:\1PBC\3SW\python39\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\parth.shah\Downloads\gujarati_speech_recognition-master\gujarati_speech_recognition-master\gui.py", line 365, in <module>
    main.mainloop()
  File "D:\1PBC\3SW\python39\lib\tkinter\__init__.py", line 1422, in mainloop
    self.tk.mainloop(n)

Please check if we can run this software in Windows as of now.
Please give your email so I can contact you faster.

**Comment by raj-sutariya** [comment]
Bug fixed. Please clone latest commit and try again.
Please make sure you have python3.7 or below in order to install right version of deepspeech.
